import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "About Page | gocapje",
  description: "Generated by create next app",
};

export default function About() {
  return (
    <div className="container">About Page</div>
  );
}