import type { Metadata } from "next";
import styles from "./home.module.css";
import HomeCarousell from "@/components/___carousell/carousell";
import Products from "@/components/home/product/product";
import PromoCard from "@/components/promo/card/card";
import BannerComponent from "@/components/home/carousell/carousell";
import Loading from "./loading";

// Add Title for HomePage

export const metadata: Metadata = {
  title: "Situs Jual Beli Online Mudah & Aman | Gocapje",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    // <div className={styles.container}>Home Page</div>
    <div className='container container-content'>
      <main>
        <>
          {/* <HomeCarousell/> */}
          <BannerComponent />
          {/* <PromoCard/> */}
          {/* <CategoryComponent/> */}
          <Products />
          {/* <div className={styles.content}>Home Page</div> */}
        </>
      </main>
    </div>
  );
}
